### ISSUE TITLE
Reports By Type

### ISSUE THREAD

**Issue by rdawes1** [ChesapeakeCommons/FISH-admin#3]
Correct me if I'm wrong but we have different types of reports for observations, bmps, benthic, and species.  Would it make sense to follow the same card pattern but then toggle between report type?

**Comment by brendandm** [comment]
There is one overall report type and each report may or may not have completed sections for vegetation, stream life, and wildlife. These 'sub-reports' are best understood in the context of a parent report and therefore will only be displayed in the detail view.
